Task 2 first steps components
crocodileDaniil/ReactEducationLearnJS pull request #2
Opened 2023-11-19 10:53 UTC by crocodileDaniil

Вы говорили не добавлять стили. Я добивил просто для удобства визуализации, могу убрать. 
хотел спросить:
1) как лучше реализовывать как в меню? - создавать большой блок меню и для каждого блюда где-то создать отдельный компонент, чтобы не засорять код (и нормальная ли практика вкладывать в саму папку меню этот компонент) или как в ревью, просто в мапе всю обработку сделать.
2) он создаёт пул реквест последнего коммита в ветке?

2023-11-20 16:45 UTC, SArchieEdu requested changes
нужно править

2023-11-20 16:45 UTC, SArchieEdu commented on src/pages/restaurants_page/component.jsx
> +  const filterArray = structuredClone(mock).map(elem => elem.name)
не очень удачный нейминг - filterArray. Тк тут нет необходимости явно указывать на структуру, просто filters достаточно

2023-11-20 16:45 UTC, SArchieEdu commented on src/components/filter_menu/component.jsx
> +export const FilterMenu = ( { filterArray, filterClick } ) => {
Будут пересечения с menu ресторанов, поэтому неминг сильно путает. RestaurantFilters подойдёт лучше

2023-11-20 16:45 UTC, SArchieEdu commented on src/components/filter_menu/component.jsx
> +export const FilterMenu = ( { filterArray, filterClick } ) => {
onFilterClick

2023-11-20 16:45 UTC, SArchieEdu commented on src/components/restaurants_window/component.jsx
> +export const RestaurantsWindow = ( { mock }) => {
Почему Window? Просто Restaurants достаточно

2023-11-20 16:45 UTC, SArchieEdu commented on src/components/restaurants_window/component.jsx
> +export const RestaurantsWindow = ( { mock }) => {
mock - такой нейминг будет путать, тк ресторан не знает о том, что это моки, для него этого нормальные данные

2023-11-20 16:45 UTC, SArchieEdu commented on src/components/restaurant_reviews/component.jsx
> +    return <li>{elem.user}:
можно без return

2023-11-20 16:45 UTC, SArchieEdu commented on src/components/restaurant_menu/dish/component.jsx
> +return <li>
тег li используется только в списке, используя его в дочернем элементе вы ограничиваете его область использования. Лучше дочерний элемент просто обернуть в него в месте использования, но не тащить в сам компонент. на лекции еще более подробно расскажу про это

2023-11-20 16:45 UTC, SArchieEdu commented on src/components/restaurant_reviews/component.jsx
> +<h3>Reviews: </h3>
лучше сделать как в меню

2023-11-20 21:35 UTC, crocodileDaniil commented on src/components/restaurants_window/component.jsx
> +export const RestaurantsWindow = ( { mock }) => {
А путанницы не будет, например RestaurantsFoods не лучше? 
или RestaurantsMenu. Restaurants звучит не слишком широко?

2023-11-20 21:42 UTC, crocodileDaniil commented on src/components/restaurant_reviews/component.jsx
> +    return <li>{elem.user}:
не понимаю как, ломается. Обычно если функция в мапе на несколько строк, то нужен return

2023-11-23 11:02 UTC, SArchieEdu approved these changes

2023-11-23 11:02 UTC, SArchieEdu commented on src/components/restaurants/component.jsx
> +  {dataFoods.map((elem) => <Restaurant data={elem}/>)}
тут скорее restaurants, тк все данные у нас data

2023-11-23 17:35 UTC, crocodileDaniil commented on src/components/restaurants/component.jsx
> +  {dataFoods.map((elem) => <Restaurant data={elem}/>)}
не совсем понял к чему, data = {elem} ?

2023-11-23 17:35 UTC, merged